
project_id = "iybnjhrsjgfbmlmvoiel"

[global]
[global.env]
SUPABASE_URL = "https://iybnjhrsjgfbmlmvoiel.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Ym5qaHJzamdmYm1sbXZvaWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODM5NDMsImV4cCI6MjA1ODk1OTk0M30.sW6080PhPNufLTRBVVF_IbW-a_2lj4Tdy-aAX1d7IDQ"
